### ISSUE TITLE
Prometheus client_ruby is GA now

### ISSUE THREAD

**Issue by Wing924** [SpencerMalone/logstash-output-prometheus#4]
Hello!

This project looks interesting and is what I want for a long time.
The Prometheus client_ruby is GA now.
https://github.com/prometheus/client_ruby/releases

Could you update the dependency?

**Comment by SpencerMalone** [comment]
Yeah! I didn't know that, will update for sure.

**Comment by SpencerMalone** [comment]
https://github.com/SpencerMalone/logstash-output-prometheus/pull/5 resolves this, I'm gonna give it a spin on our logstash instances and see how it do!

**Comment by SpencerMalone** [comment]
Update: So far so good, I'm gonna close this out in a few days, unless you think otherwise?
