### ISSUE TITLE
Possibility to get logstash internal metrics?

### ISSUE THREAD

**Issue by ghost** [SpencerMalone/logstash-output-prometheus#9]
Hi,

Is it possible to send logstash internal metrics to prometheus? I would like to get similar details as from curl -XGET 'localhost:9600/_node/stats/pipelines/main?pretty'

Regards
Steffen

**Comment by steffakasid** [comment]
Sorry messed up my accounts. But I'm still here.

**Comment by cydergoth** [comment]
You may do this by using the http_poller to callback to the logstash metrics API, but it would be nicer to have built-in support in this output for all those metrics

**Comment by SpencerMalone** [comment]
Sadly this is focused purely on exporting data from pipelines! I think there are some prometheus logstash exporters out there that focus more on exporting the state of logstash into prometheus
